### ISSUE TITLE
Community-based naming scheme

### ISSUE THREAD

**Issue by MathewSachin** [minhducsun2002/boomer#3]
Right now, `b!s` command searches servants using fuzzy matching, which isn't correct in all cases.
Names should be customizable like in the great Wizard bot.

Example: `b!addname 283 lici` where 283 is the ID of Erice.

**Comment by minhducsun2002** [comment]
Implemented in commits from 8d8b57200b2a3928e3613875ef8aac7503406ae9 to d9d8dafdd7a3ff5f4f761db9a072d34a2696c4b8.
